name: Code Quality

on:
  push:

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js project
        uses: pnpm/setup@v2
        with:
          version: 11
          runtime: node@24
          cache: true
          require-lockfile: true

      - name: Run ESLint
        run: pnpm run lint
        continue-on-error: false

      - name: Run Prettier check
        run: pnpm exec prettier --check .
        continue-on-error: false

      - name: Run tests
        run: pnpm run test
        continue-on-error: false
